version: "3.9"

services:
  db:
    build:
      context: ./infra/docker/db
      dockerfile: Dockerfile
    container_name: "python-be-syokyu-db"
    hostname: db
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: python_be_syokyu
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - python-be-syokyu-db-data:/var/lib/mysql
      - ./infra/docker/db/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./infra/docker/db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - ${DOCKER_DB_PORT:-23306}:3306
    tty: true

  app:
    container_name: "python-be-syokyu-app"
    depends_on:
      - db
    build:
      context: ./infra/docker/app
      dockerfile: Dockerfile
      target: ${APP_BUILD_TARGET:-dev}
    environment:
      DEBUG: true
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
    ports:
      - "${APP_PORT:-18008}:${APP_PORT:-18008}"
    volumes:
      - .:/opt/python-be-syokyu-app
    command: fastapi dev main.py --port=${APP_PORT:-18008} --host=0.0.0.0

  adminer:
    image: adminer
    restart: always
    ports:
      - 38080:8080
    environment:
        ADMINER_DEFAULT_SERVER: db
        ADMINER_DESIGN: galkaev

volumes:
  python-be-syokyu-db-data:
    driver: local